In [2]:
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
import joblib
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
file = os.path.join('C:/Users/victo/OneDrive/Escritorio/Estudios USM/Ingenieria/Computacion aplicada/Chancador trabajo computacion/', 'Chancador_Raw_Data.csv')
df1 = pd.read_csv(file)
attrs = {
	'var': 'df1',
	'type': type(df1).__name__,
}
[attrs]
df1

C:\Users\victo\AppData\Local\Temp\ipykernel_11100\1447478515.py:2: DtypeWarning: Columns (4,5,6,10,11,16,17,18,20,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(file)

[{'var': 'df1', 'type': 'DataFrame'}]

,Unnamed: 0,Tiempo,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto Anillo,...,Nivel Taza,Setting,Corriente.1,Pesómetro,Corriente.2,V. Cero,Corriente.3,V. Cero.1,Corriente.4,V. Cero.2
0,0,2017-07-01 08:00:00,67.05307006835938,362.78125,39.60781478881836,36.28849029541016,55.49257659912109,34.39426040649414,34.88699340820312,7.641797065734863,...,40.26848220825195,28.60000610351562,45,2275.893310546875,84.06780242919922,101.5626068115234,39.59999847412109,94.04566955566406,Bad Input,0.3102322518825531
1,1,2017-07-01 08:02:00,59.17750549316406,387.68359375,39.49625015258789,36.19640731811523,55.34035873413086,34.04961013793945,34.83254241943359,7.492578029632568,...,40.79876327514648,28.60000610351562,46,2300.636962890625,83.05084991455078,101.5591583251953,40,90.39868927001953,Bad Input,0.3104053437709808
2,2,2017-07-01 08:04:00,63.52828216552734,305.9140625,39.35148620605469,36.12993240356445,55.47822570800781,33.91414260864258,34.7747688293457,7.526171684265137,...,40.99420166015625,28.60000610351562,45,2259.741455078125,83.05084991455078,101.4512939453125,40,89.26689910888672,Bad Input,0.3102254867553711
3,3,2017-07-01 08:06:00,65.61479187011719,360.4296875,39.30965042114258,36.00020599365234,55.26688385009766,33.76937484741211,34.65125274658203,7.255859375,...,40.18500518798828,28.60000610351562,45.40000152587891,2412.8974609375,86.440673828125,101.2942047119141,41,96.05992889404297,Bad Input,0.3109926283359528
4,4,2017-07-01 08:08:00,68.3459243774414,318.9921875,39.19012069702148,36.00524520874023,55.60165023803711,33.6657829284668,34.54035186767578,7.751172065734863,...,40.91349411010742,28.60000610351562,46.59999847412109,2487.29345703125,88.1355972290039,101.3100662231445,41.40000152587891,95.88184356689453,Bad Input,0.3103735744953156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,60723,2019-09-23 17:06:00,0,1.80078125,33.85968780517578,37.81310653686523,47.38640594482422,29.54062652587891,22.3793773651123,-0.07421875,...,Bad Input,32.20000457763672,Bad Input,-28.52626609802246,0,-0.2583421468734741,Bad Input,-0.466058611869812,Bad Input,0.4079932272434235
1048571,60724,2019-09-23 17:08:00,0,1.81640625,33.79726791381836,37.80581665039062,47.36933517456055,29.28695487976074,22.37539291381836,-0.07421875,...,Bad Input,32.20000457763672,Bad Input,-28.52626609802246,0,-0.2614571452140808,Bad Input,-0.4668164253234863,Bad Input,0.4085834622383118
1048572,60725,2019-09-23 17:10:00,0,1.84765625,33.82914352416992,37.8098258972168,47.35480117797852,29.22320556640625,22.39398574829102,-0.07421875,...,Bad Input,32.20000457763672,Bad Input,-28.52626609802246,0,-0.2594147324562073,Bad Input,-0.4706054925918579,Bad Input,0.4086388945579529
1048573,60726,2019-09-23 17:12:00,0,1.85546875,33.98719024658203,37.85100936889648,47.34027099609375,29.23515892028809,22.33023643493652,-0.07421875,...,Bad Input,32.20000457763672,Bad Input,-28.52626609802246,0,-0.2595284879207611,Bad Input,-0.4706054925918579,Bad Input,0.4078384935855865
1048574,60727,2019-09-23 17:14:00,0,1.81640625,34.07351684570312,37.85064315795898,47.32828140258789,28.99078369140625,22.3129711151123,-0.07421875,...,Bad Input,32.20000457763672,Bad Input,-28.52626609802246,0,-0.258770078420639,Bad Input,-0.4668164253234863,Bad Input,0.4062333405017853

In [4]:
df1 = df1.drop([
	'Unnamed: 0',
	'V. Cero.2',
	'Corriente.4',
	'V. Cero.1',
	'Corriente.3',
	'V. Cero',
	'Pesómetro',
	'Corriente.2',
	'Corriente.1',
], axis='columns')
attrs = {
	'var': 'df1',
	'type': type(df1).__name__,
}
[attrs]
df1

[{'var': 'df1', 'type': 'DataFrame'}]

,Tiempo,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto Anillo,Unnamed: 9,Unnamed: 10,Unnamed: 11,Nivel Taza,Setting
0,2017-07-01 08:00:00,67.05307006835938,362.78125,39.60781478881836,36.28849029541016,55.49257659912109,34.39426040649414,34.88699340820312,7.641797065734863,10.31718730926514,6.255078315734863,14.70351600646973,40.26848220825195,28.60000610351562
1,2017-07-01 08:02:00,59.17750549316406,387.68359375,39.49625015258789,36.19640731811523,55.34035873413086,34.04961013793945,34.83254241943359,7.492578029632568,9.986719131469727,5.973828315734863,13.18476581573486,40.79876327514648,28.60000610351562
2,2017-07-01 08:04:00,63.52828216552734,305.9140625,39.35148620605469,36.12993240356445,55.47822570800781,33.91414260864258,34.7747688293457,7.526171684265137,10.84414100646973,6.708593845367432,14.61250019073486,40.99420166015625,28.60000610351562
3,2017-07-01 08:06:00,65.61479187011719,360.4296875,39.30965042114258,36.00020599365234,55.26688385009766,33.76937484741211,34.65125274658203,7.255859375,9.587109565734863,6.538281440734863,13.70585918426514,40.18500518798828,28.60000610351562
4,2017-07-01 08:08:00,68.3459243774414,318.9921875,39.19012069702148,36.00524520874023,55.60165023803711,33.6657829284668,34.54035186767578,7.751172065734863,10.17617225646973,7.362890720367432,14.80859375,40.91349411010742,28.60000610351562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2019-09-23 17:06:00,0,1.80078125,33.85968780517578,37.81310653686523,47.38640594482422,29.54062652587891,22.3793773651123,-0.07421875,0.01171875,-0.0546875,-0.060546875,Bad Input,32.20000457763672
1048571,2019-09-23 17:08:00,0,1.81640625,33.79726791381836,37.80581665039062,47.36933517456055,29.28695487976074,22.37539291381836,-0.07421875,0.01171875,-0.0546875,-0.060546875,Bad Input,32.20000457763672
1048572,2019-09-23 17:10:00,0,1.84765625,33.82914352416992,37.8098258972168,47.35480117797852,29.22320556640625,22.39398574829102,-0.07421875,0.01171875,-0.0546875,-0.060546875,Bad Input,32.20000457763672
1048573,2019-09-23 17:12:00,0,1.85546875,33.98719024658203,37.85100936889648,47.34027099609375,29.23515892028809,22.33023643493652,-0.07421875,0.01171875,-0.0546875,-0.060546875,Bad Input,32.20000457763672
1048574,2019-09-23 17:14:00,0,1.81640625,34.07351684570312,37.85064315795898,47.32828140258789,28.99078369140625,22.3129711151123,-0.07421875,0.008593750186264515,-0.0546875,-0.060546875,Bad Input,32.20000457763672

In [5]:
df1 = df1.rename(columns={
	'Salto Anillo': 'Salto anillo A',
	'Unnamed: 9': 'Salto anillo B',
	'Unnamed: 10': 'Salto anillo C',
	'Unnamed: 11': 'Salto anillo D',
})
attrs = {
	'var': 'df1',
	'type': type(df1).__name__,
}
[attrs]
df1

[{'var': 'df1', 'type': 'DataFrame'}]

,Tiempo,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
0,2017-07-01 08:00:00,67.05307006835938,362.78125,39.60781478881836,36.28849029541016,55.49257659912109,34.39426040649414,34.88699340820312,7.641797065734863,10.31718730926514,6.255078315734863,14.70351600646973,40.26848220825195,28.60000610351562
1,2017-07-01 08:02:00,59.17750549316406,387.68359375,39.49625015258789,36.19640731811523,55.34035873413086,34.04961013793945,34.83254241943359,7.492578029632568,9.986719131469727,5.973828315734863,13.18476581573486,40.79876327514648,28.60000610351562
2,2017-07-01 08:04:00,63.52828216552734,305.9140625,39.35148620605469,36.12993240356445,55.47822570800781,33.91414260864258,34.7747688293457,7.526171684265137,10.84414100646973,6.708593845367432,14.61250019073486,40.99420166015625,28.60000610351562
3,2017-07-01 08:06:00,65.61479187011719,360.4296875,39.30965042114258,36.00020599365234,55.26688385009766,33.76937484741211,34.65125274658203,7.255859375,9.587109565734863,6.538281440734863,13.70585918426514,40.18500518798828,28.60000610351562
4,2017-07-01 08:08:00,68.3459243774414,318.9921875,39.19012069702148,36.00524520874023,55.60165023803711,33.6657829284668,34.54035186767578,7.751172065734863,10.17617225646973,7.362890720367432,14.80859375,40.91349411010742,28.60000610351562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2019-09-23 17:06:00,0,1.80078125,33.85968780517578,37.81310653686523,47.38640594482422,29.54062652587891,22.3793773651123,-0.07421875,0.01171875,-0.0546875,-0.060546875,Bad Input,32.20000457763672
1048571,2019-09-23 17:08:00,0,1.81640625,33.79726791381836,37.80581665039062,47.36933517456055,29.28695487976074,22.37539291381836,-0.07421875,0.01171875,-0.0546875,-0.060546875,Bad Input,32.20000457763672
1048572,2019-09-23 17:10:00,0,1.84765625,33.82914352416992,37.8098258972168,47.35480117797852,29.22320556640625,22.39398574829102,-0.07421875,0.01171875,-0.0546875,-0.060546875,Bad Input,32.20000457763672
1048573,2019-09-23 17:12:00,0,1.85546875,33.98719024658203,37.85100936889648,47.34027099609375,29.23515892028809,22.33023643493652,-0.07421875,0.01171875,-0.0546875,-0.060546875,Bad Input,32.20000457763672
1048574,2019-09-23 17:14:00,0,1.81640625,34.07351684570312,37.85064315795898,47.32828140258789,28.99078369140625,22.3129711151123,-0.07421875,0.008593750186264515,-0.0546875,-0.060546875,Bad Input,32.20000457763672

In [6]:
df1 = df1
s = df1['Tiempo']
df1['Tiempo'] = pd.to_datetime(s, errors='coerce')

s = df1['Corriente']
df1['Corriente'] = pd.to_numeric(s, errors='coerce')

s = df1['Presión C. Eje']
df1['Presión C. Eje'] = pd.to_numeric(s, errors='coerce')

s = df1['T° Retorno']
df1['T° Retorno'] = pd.to_numeric(s, errors='coerce')

s = df1['T° socket Linner']
df1['T° socket Linner'] = pd.to_numeric(s, errors='coerce')

s = df1['T° Excéntrica']
df1['T° Excéntrica'] = pd.to_numeric(s, errors='coerce')

s = df1['T° Alimentación']
df1['T° Alimentación'] = pd.to_numeric(s, errors='coerce')

s = df1['T° Desc. C. Eje']
df1['T° Desc. C. Eje'] = pd.to_numeric(s, errors='coerce')

s = df1['Salto anillo A']
df1['Salto anillo A'] = pd.to_numeric(s, errors='coerce')

s = df1['Salto anillo B']
df1['Salto anillo B'] = pd.to_numeric(s, errors='coerce')

s = df1['Salto anillo C']
df1['Salto anillo C'] = pd.to_numeric(s, errors='coerce')

s = df1['Salto anillo D']
df1['Salto anillo D'] = pd.to_numeric(s, errors='coerce')

s = df1['Nivel Taza']
df1['Nivel Taza'] = pd.to_numeric(s, errors='coerce')

s = df1['Setting']
df1['Setting'] = pd.to_numeric(s, errors='coerce')

attrs = {
	'var': 'df1',
	'type': type(df1).__name__,
}
[attrs]
df1

[{'var': 'df1', 'type': 'DataFrame'}]

,Tiempo,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
0,2017-07-01 08:00:00,67.053070,362.781250,39.607815,36.288490,55.492577,34.394260,34.886993,7.641797,10.317187,6.255078,14.703516,40.268482,28.600006
1,2017-07-01 08:02:00,59.177505,387.683594,39.496250,36.196407,55.340359,34.049610,34.832542,7.492578,9.986719,5.973828,13.184766,40.798763,28.600006
2,2017-07-01 08:04:00,63.528282,305.914062,39.351486,36.129932,55.478226,33.914143,34.774769,7.526172,10.844141,6.708594,14.612500,40.994202,28.600006
3,2017-07-01 08:06:00,65.614792,360.429688,39.309650,36.000206,55.266884,33.769375,34.651253,7.255859,9.587110,6.538281,13.705859,40.185005,28.600006
4,2017-07-01 08:08:00,68.345924,318.992188,39.190121,36.005245,55.601650,33.665783,34.540352,7.751172,10.176172,7.362891,14.808594,40.913494,28.600006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2019-09-23 17:06:00,0.000000,1.800781,33.859688,37.813107,47.386406,29.540627,22.379377,-0.074219,0.011719,-0.054688,-0.060547,NaN,32.200005
1048571,2019-09-23 17:08:00,0.000000,1.816406,33.797268,37.805817,47.369335,29.286955,22.375393,-0.074219,0.011719,-0.054688,-0.060547,NaN,32.200005
1048572,2019-09-23 17:10:00,0.000000,1.847656,33.829144,37.809826,47.354801,29.223206,22.393986,-0.074219,0.011719,-0.054688,-0.060547,NaN,32.200005
1048573,2019-09-23 17:12:00,0.000000,1.855469,33.987190,37.851009,47.340271,29.235159,22.330236,-0.074219,0.011719,-0.054688,-0.060547,NaN,32.200005
1048574,2019-09-23 17:14:00,0.000000,1.816406,34.073517,37.850643,47.328281,28.990784,22.312971,-0.074219,0.008594,-0.054688,-0.060547,NaN,32.200005

In [7]:
df1 = df1.dropna(axis='index')

attrs = {
	'var': 'df1',
	'type': type(df1).__name__,
}
[attrs]
df1

[{'var': 'df1', 'type': 'DataFrame'}]

,Tiempo,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
0,2017-07-01 08:00:00,67.053070,362.781250,39.607815,36.288490,55.492577,34.394260,34.886993,7.641797,10.317187,6.255078,14.703516,40.268482,28.600006
1,2017-07-01 08:02:00,59.177505,387.683594,39.496250,36.196407,55.340359,34.049610,34.832542,7.492578,9.986719,5.973828,13.184766,40.798763,28.600006
2,2017-07-01 08:04:00,63.528282,305.914062,39.351486,36.129932,55.478226,33.914143,34.774769,7.526172,10.844141,6.708594,14.612500,40.994202,28.600006
3,2017-07-01 08:06:00,65.614792,360.429688,39.309650,36.000206,55.266884,33.769375,34.651253,7.255859,9.587110,6.538281,13.705859,40.185005,28.600006
4,2017-07-01 08:08:00,68.345924,318.992188,39.190121,36.005245,55.601650,33.665783,34.540352,7.751172,10.176172,7.362891,14.808594,40.913494,28.600006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872093,2019-05-06 12:34:00,0.000000,217.148438,34.072269,35.137676,41.315334,32.226566,29.100393,0.087891,0.275391,0.082031,0.305664,27.349173,51.299965
872094,2019-05-06 12:36:00,0.000000,210.371094,34.305470,35.364925,41.157520,33.551567,28.854691,0.134766,0.360352,0.125000,0.437500,28.305700,51.299965
872095,2019-05-06 12:38:00,0.000000,208.222656,34.530472,35.413589,41.037106,34.060547,28.853909,0.140625,0.392578,0.177734,0.459961,0.260094,51.299965
872096,2019-05-06 12:40:00,0.000000,205.507812,34.852345,35.491409,40.935600,34.508595,28.867971,0.125000,0.342773,0.158203,0.433594,28.762465,51.299965
872097,2019-05-06 12:42:00,0.000000,203.242188,35.078518,35.553905,40.833134,34.734375,28.859299,-0.054688,-0.037109,-0.023438,0.001953,28.078117,51.299965

In [8]:
df1 = df1
df1.set_index([
	'Tiempo',
], inplace=True)
attrs = {
	'var': 'df1',
	'type': type(df1).__name__,
}
[attrs]
df1

[{'var': 'df1', 'type': 'DataFrame'}]

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
Tiempo,,,,,,,,,,,,,
2017-07-01 08:00:00,67.053070,362.781250,39.607815,36.288490,55.492577,34.394260,34.886993,7.641797,10.317187,6.255078,14.703516,40.268482,28.600006
2017-07-01 08:02:00,59.177505,387.683594,39.496250,36.196407,55.340359,34.049610,34.832542,7.492578,9.986719,5.973828,13.184766,40.798763,28.600006
2017-07-01 08:04:00,63.528282,305.914062,39.351486,36.129932,55.478226,33.914143,34.774769,7.526172,10.844141,6.708594,14.612500,40.994202,28.600006
2017-07-01 08:06:00,65.614792,360.429688,39.309650,36.000206,55.266884,33.769375,34.651253,7.255859,9.587110,6.538281,13.705859,40.185005,28.600006
2017-07-01 08:08:00,68.345924,318.992188,39.190121,36.005245,55.601650,33.665783,34.540352,7.751172,10.176172,7.362891,14.808594,40.913494,28.600006
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-05-06 12:34:00,0.000000,217.148438,34.072269,35.137676,41.315334,32.226566,29.100393,0.087891,0.275391,0.082031,0.305664,27.349173,51.299965
2019-05-06 12:36:00,0.000000,210.371094,34.305470,35.364925,41.157520,33.551567,28.854691,0.134766,0.360352,0.125000,0.437500,28.305700,51.299965
2019-05-06 12:38:00,0.000000,208.222656,34.530472,35.413589,41.037106,34.060547,28.853909,0.140625,0.392578,0.177734,0.459961,0.260094,51.299965
2019-05-06 12:40:00,0.000000,205.507812,34.852345,35.491409,40.935600,34.508595,28.867971,0.125000,0.342773,0.158203,0.433594,28.762465,51.299965
2019-05-06 12:42:00,0.000000,203.242188,35.078518,35.553905,40.833134,34.734375,28.859299,-0.054688,-0.037109,-0.023438,0.001953,28.078117,51.299965

In [9]:
df19 = df1.resample('4T')

attrs = {
	'var': 'df19',
	'type': type(df19).__name__,
}
[attrs]
df19
enum = enumerate(df19.groups)
nextel = next(enum)
nextel[1]
df19.get_group(nextel[1])
nextel = next(enum)
nextel[1]
df19.get_group(nextel[1])

C:\Users\victo\AppData\Local\Temp\ipykernel_11100\1706253134.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df19 = df1.resample('4T')

[{'var': 'df19', 'type': 'DatetimeIndexResampler'}]

Timestamp('2017-07-01 08:00:00')

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
Tiempo,,,,,,,,,,,,,
2017-07-01 08:00:00,67.053070,362.781250,39.607815,36.288490,55.492577,34.39426,34.886993,7.641797,10.317187,6.255078,14.703516,40.268482,28.600006
2017-07-01 08:02:00,59.177505,387.683594,39.496250,36.196407,55.340359,34.04961,34.832542,7.492578,9.986719,5.973828,13.184766,40.798763,28.600006

Timestamp('2017-07-01 08:04:00')

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
Tiempo,,,,,,,,,,,,,
2017-07-01 08:04:00,63.528282,305.914062,39.351486,36.129932,55.478226,33.914143,34.774769,7.526172,10.844141,6.708594,14.612500,40.994202,28.600006
2017-07-01 08:06:00,65.614792,360.429688,39.309650,36.000206,55.266884,33.769375,34.651253,7.255859,9.587110,6.538281,13.705859,40.185005,28.600006

In [10]:
df19 = df19.aggregate('median')

attrs = {
	'var': 'df19',
	'type': type(df19).__name__,
}
[attrs]
df19

[{'var': 'df19', 'type': 'DataFrame'}]

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
Tiempo,,,,,,,,,,,,,
2017-07-01 08:00:00,63.115288,375.232422,39.552032,36.242449,55.416468,34.221935,34.859768,7.567188,10.151953,6.114453,13.944141,40.533623,28.600006
2017-07-01 08:04:00,64.571537,333.171875,39.330568,36.065069,55.372555,33.841759,34.713011,7.391016,10.215625,6.623438,14.159180,40.589603,28.600006
2017-07-01 08:08:00,68.713585,331.572266,39.133841,35.957037,55.562643,33.637228,34.487892,7.608008,9.920898,6.798242,13.736719,39.943991,28.600006
2017-07-01 08:12:00,47.131349,404.742188,39.342024,35.770777,55.108313,34.304115,34.501839,4.427148,5.851953,3.587695,7.779688,38.609440,28.880005
2017-07-01 08:16:00,38.784102,394.951172,40.237015,36.337887,54.946651,35.115929,34.984612,3.902734,4.977344,3.455078,7.332617,30.456848,28.500004
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-05-06 12:24:00,0.000000,210.273438,34.768362,35.902653,42.288504,32.613281,29.808596,0.104492,0.310547,0.118652,0.389648,49.927901,51.299965
2019-05-06 12:28:00,0.000000,214.345703,34.453516,35.566711,41.824305,32.442581,29.482814,0.115234,0.342285,0.137207,0.410156,27.432148,51.299965
2019-05-06 12:32:00,0.000000,216.791992,34.121096,35.219732,41.416786,32.187111,29.176955,0.093750,0.270508,0.097656,0.313965,27.713891,51.299965
2019-05-06 12:36:00,0.000000,209.296875,34.417971,35.389257,41.097313,33.806057,28.854300,0.137695,0.376465,0.151367,0.448730,14.282897,51.299965
2019-05-06 12:40:00,0.000000,204.375000,34.965431,35.522657,40.884367,34.621485,28.863635,0.035156,0.152832,0.067383,0.217773,28.420291,51.299965

In [11]:
file = os.path.join('C:/Users/victo/OneDrive/Escritorio/', 'Chantadorcomputacionaplicada4M.csv')
df19.to_csv(file)
attrs = {
	'var': 'empty',
	'type': 'empty',
}
[attrs]
'csv file saved'

[{'var': 'empty', 'type': 'empty'}]

'csv file saved'

In [12]:
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
import joblib
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [13]:
file = os.path.join('C:/Users/victo/OneDrive/Escritorio/Estudios USM/Ingenieria/Computacion aplicada/Chancador trabajo computacion/', 'DetencionesRev.xlsx')
df9 = pd.read_excel(file, header=0)
attrs = {
	'var': 'df9',
	'type': type(df9).__name__,
}
[attrs]
df9

[{'var': 'df9', 'type': 'DataFrame'}]

,Unnamed: 0,Día,Fecha,Tipo de Detención,Detalle de Reporte,Equipo,Causa,Inicio,Fin,Tiempo Detención (hrs),Tipo de Detención (2),MES,Año,Estado
0,0,2,2017-01-02,Falla,L3 \ \ Correa 004,130-CV-004,Falla Control e Instrumentación,2017-01-02 12:42:40,2017-01-02 13:05:50,0.386111,1,1,2017,NaN
1,1,2,2017-01-02,Operacional,L3 \ \ Feeder 130-FE-006,130-FE-006,Otra Causa,2017-01-02 14:47:50,2017-01-02 14:51:02,0.053333,0,1,2017,NaN
2,2,2,2017-01-02,Falla,L3 \ \ Correa 004,130-CV-004,Otra Causa,2017-01-02 16:10:02,2017-01-03 00:32:50,8.380000,1,1,2017,NaN
3,3,2,2017-01-02,Operacional,L3 \ \ Feeder 130-FE-006,130-FE-006,Otra Causa,2017-01-03 01:58:20,2017-01-03 02:08:02,0.161667,0,1,2017,NaN
4,4,2,2017-01-02,Bajo Stock Mina,L3 \ \ Sistema,Sistema,Bajo Stock Mina,2017-01-03 05:21:30,2017-01-03 05:46:50,0.422222,0,1,2017,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2590,2590,22,2019-08-22,Bajo Stock Mina,L3 \ \ Sistema,Sistema,Bajo Stock Mina,2019-08-22 10:48:15,2019-08-23 08:00:00,21.195833,0,8,2019,NaN
2591,2591,23,2019-08-23,Bajo Stock Mina,L3 \ \ Sistema,Sistema,Mantención Programada,2019-08-23 08:00:00,2019-08-26 08:00:00,72.000000,0,8,2019,NaN
2592,2592,26,2019-08-26,Bajo Stock Mina,L3 \ \ Sistema,Sistema,Retraso Mantención Programada,2019-08-26 08:00:00,2019-08-26 16:16:15,8.270833,0,8,2019,NaN
2593,2593,29,2019-08-29,Operacional,L3 \ \ Sistema,Sistema,Enclavamiento,2019-08-29 11:29:45,2019-08-29 15:40:55,4.186111,0,8,2019,NaN
2594,2594,31,2019-08-31,Operacional,L3 \ \ Sistema,Sistema,Enclavamiento,2019-08-31 15:28:45,2019-08-31 19:23:25,3.911111,0,8,2019,NaN

In [14]:
df9 = df9.drop([
	'Tipo de Detención (2)',
	'MES',
	'Estado',
	'Año',
	'Tiempo Detención (hrs)',
	'Unnamed: 0',
	'Detalle de Reporte',
	'Día',
	'Fecha',
], axis='columns')
attrs = {
	'var': 'df9',
	'type': type(df9).__name__,
}
[attrs]
df9

[{'var': 'df9', 'type': 'DataFrame'}]

,Tipo de Detención,Equipo,Causa,Inicio,Fin
0,Falla,130-CV-004,Falla Control e Instrumentación,2017-01-02 12:42:40,2017-01-02 13:05:50
1,Operacional,130-FE-006,Otra Causa,2017-01-02 14:47:50,2017-01-02 14:51:02
2,Falla,130-CV-004,Otra Causa,2017-01-02 16:10:02,2017-01-03 00:32:50
3,Operacional,130-FE-006,Otra Causa,2017-01-03 01:58:20,2017-01-03 02:08:02
4,Bajo Stock Mina,Sistema,Bajo Stock Mina,2017-01-03 05:21:30,2017-01-03 05:46:50
...,...,...,...,...,...
2590,Bajo Stock Mina,Sistema,Bajo Stock Mina,2019-08-22 10:48:15,2019-08-23 08:00:00
2591,Bajo Stock Mina,Sistema,Mantención Programada,2019-08-23 08:00:00,2019-08-26 08:00:00
2592,Bajo Stock Mina,Sistema,Retraso Mantención Programada,2019-08-26 08:00:00,2019-08-26 16:16:15
2593,Operacional,Sistema,Enclavamiento,2019-08-29 11:29:45,2019-08-29 15:40:55
2594,Operacional,Sistema,Enclavamiento,2019-08-31 15:28:45,2019-08-31 19:23:25

In [15]:
cond = ((df9['Equipo'].eq('130-CV-004')))
df9 = df9[cond]
attrs = {
	'var': 'df9',
	'type': type(df9).__name__,
}
[attrs]
df9

[{'var': 'df9', 'type': 'DataFrame'}]

,Tipo de Detención,Equipo,Causa,Inicio,Fin
0,Falla,130-CV-004,Falla Control e Instrumentación,2017-01-02 12:42:40,2017-01-02 13:05:50
2,Falla,130-CV-004,Otra Causa,2017-01-02 16:10:02,2017-01-03 00:32:50
32,Falla,130-CV-004,Otra Causa,2017-01-07 11:35:50,2017-01-07 13:39:30
33,Falla,130-CV-004,Falla Eléctrica,2017-01-08 11:15:30,2017-01-08 11:18:40
42,Falla,130-CV-004,Falla Control e Instrumentación,2017-01-12 05:37:20,2017-01-12 06:41:10
...,...,...,...,...,...
2497,Falla,130-CV-004,Falla Eléctrica,2018-12-22 02:02:01,2018-12-22 02:05:10
2522,Operacional,130-CV-004,Desalineamiento,2019-01-01 04:09:10,2019-01-01 04:13:50
2545,Falla,130-CV-004,Falla Mecánica,2019-02-16 08:25:15,2019-02-16 18:35:35
2547,Falla,130-CV-004,Falla Eléctrica,2019-02-18 09:00:30,2019-02-18 13:12:25
2555,Falla,130-CV-004,Falla Control e Instrumentación,2019-03-08 17:25:05,2019-03-08 22:24:55

In [16]:
df9 = df9
cond = ((df9['Tipo de Detención'].isin(["Operacional", "Mantencion Programada"])))
df9['Tipo de Detención'].mask(cond, other='Pausa', inplace=True)

attrs = {
	'var': 'df9',
	'type': type(df9).__name__,
}
[attrs]
df9

C:\Users\victo\AppData\Local\Temp\ipykernel_11100\1713976514.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df9['Tipo de Detención'].mask(cond, other='Pausa', inplace=True)
C:\Users\victo\AppData\Local\Temp\ipykernel_11100\1713976514.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df9['Tipo de Detención'].mask(cond, other='Pausa', inplace=True)

[{'var': 'df9', 'type': 'DataFrame'}]

,Tipo de Detención,Equipo,Causa,Inicio,Fin
0,Falla,130-CV-004,Falla Control e Instrumentación,2017-01-02 12:42:40,2017-01-02 13:05:50
2,Falla,130-CV-004,Otra Causa,2017-01-02 16:10:02,2017-01-03 00:32:50
32,Falla,130-CV-004,Otra Causa,2017-01-07 11:35:50,2017-01-07 13:39:30
33,Falla,130-CV-004,Falla Eléctrica,2017-01-08 11:15:30,2017-01-08 11:18:40
42,Falla,130-CV-004,Falla Control e Instrumentación,2017-01-12 05:37:20,2017-01-12 06:41:10
...,...,...,...,...,...
2497,Falla,130-CV-004,Falla Eléctrica,2018-12-22 02:02:01,2018-12-22 02:05:10
2522,Pausa,130-CV-004,Desalineamiento,2019-01-01 04:09:10,2019-01-01 04:13:50
2545,Falla,130-CV-004,Falla Mecánica,2019-02-16 08:25:15,2019-02-16 18:35:35
2547,Falla,130-CV-004,Falla Eléctrica,2019-02-18 09:00:30,2019-02-18 13:12:25
2555,Falla,130-CV-004,Falla Control e Instrumentación,2019-03-08 17:25:05,2019-03-08 22:24:55

In [17]:
import os
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
import joblib
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [18]:
file = os.path.join('C:/Users/victo/OneDrive/Escritorio/Estudios USM/Ingenieria/Computacion aplicada/Chancador trabajo computacion/', 'Chantadorcomputacionaplicada12M.csv')
df10 = pd.read_csv(file, header=0)
attrs = {
	'var': 'df10',
	'type': type(df10).__name__,
}
[attrs]
df10

[{'var': 'df10', 'type': 'DataFrame'}]

,Tiempo,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
0,2017-07-01 08:00:00,6.633393e+01,352.291016,39.330568,36.067589,55.485401,33.841759,34.713011,7.509375,10.081446,6.396680,14.159180,40.533623,28.600006
1,2017-07-01 08:12:00,5.873533e+01,371.410156,40.237015,36.454180,55.306391,35.115929,34.984612,6.826367,8.688281,6.017188,12.778320,40.410822,28.500004
2,2017-07-01 08:24:00,7.330124e+01,306.683594,42.924143,39.803396,57.962978,38.862738,36.497345,7.344141,9.495117,6.327344,13.664258,40.086174,28.500004
3,2017-07-01 08:36:00,7.359566e+01,263.185547,44.400021,41.389423,59.253897,40.636448,37.869467,7.599805,9.619336,7.019141,13.967968,41.802011,28.500004
4,2017-07-01 08:48:00,7.216714e+01,300.306641,43.409241,40.016947,57.869795,37.751429,38.141232,7.640820,9.582422,6.680078,13.574414,41.188478,28.500004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80899,2019-05-06 11:48:00,3.816504e-28,191.533203,40.859182,39.509026,53.035002,38.809961,33.665823,0.247559,0.545898,0.271484,0.688477,12.427644,51.299965
80900,2019-05-06 12:00:00,0.000000e+00,187.421875,37.240042,38.162100,45.844812,34.772854,32.221487,0.134766,0.362793,0.154785,0.394531,3.659730,51.299965
80901,2019-05-06 12:12:00,0.000000e+00,203.500977,35.421877,36.641315,43.335768,33.321487,30.623049,0.122070,0.319824,0.126465,0.371094,11.449250,51.299965
80902,2019-05-06 12:24:00,0.000000e+00,214.321289,34.453516,35.566711,41.824305,32.437502,29.482814,0.099609,0.308594,0.122559,0.379883,27.432148,51.299965
80903,2019-05-06 12:36:00,0.000000e+00,206.865234,34.691408,35.452499,40.986353,34.284571,28.856995,0.129883,0.351562,0.141602,0.435547,28.191909,51.299965

In [19]:
df10 = df10
s = df10['Tiempo']
df10['Tiempo'] = pd.to_datetime(s, errors='coerce')

attrs = {
	'var': 'df10',
	'type': type(df10).__name__,
}
[attrs]
df10

[{'var': 'df10', 'type': 'DataFrame'}]

,Tiempo,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
0,2017-07-01 08:00:00,6.633393e+01,352.291016,39.330568,36.067589,55.485401,33.841759,34.713011,7.509375,10.081446,6.396680,14.159180,40.533623,28.600006
1,2017-07-01 08:12:00,5.873533e+01,371.410156,40.237015,36.454180,55.306391,35.115929,34.984612,6.826367,8.688281,6.017188,12.778320,40.410822,28.500004
2,2017-07-01 08:24:00,7.330124e+01,306.683594,42.924143,39.803396,57.962978,38.862738,36.497345,7.344141,9.495117,6.327344,13.664258,40.086174,28.500004
3,2017-07-01 08:36:00,7.359566e+01,263.185547,44.400021,41.389423,59.253897,40.636448,37.869467,7.599805,9.619336,7.019141,13.967968,41.802011,28.500004
4,2017-07-01 08:48:00,7.216714e+01,300.306641,43.409241,40.016947,57.869795,37.751429,38.141232,7.640820,9.582422,6.680078,13.574414,41.188478,28.500004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80899,2019-05-06 11:48:00,3.816504e-28,191.533203,40.859182,39.509026,53.035002,38.809961,33.665823,0.247559,0.545898,0.271484,0.688477,12.427644,51.299965
80900,2019-05-06 12:00:00,0.000000e+00,187.421875,37.240042,38.162100,45.844812,34.772854,32.221487,0.134766,0.362793,0.154785,0.394531,3.659730,51.299965
80901,2019-05-06 12:12:00,0.000000e+00,203.500977,35.421877,36.641315,43.335768,33.321487,30.623049,0.122070,0.319824,0.126465,0.371094,11.449250,51.299965
80902,2019-05-06 12:24:00,0.000000e+00,214.321289,34.453516,35.566711,41.824305,32.437502,29.482814,0.099609,0.308594,0.122559,0.379883,27.432148,51.299965
80903,2019-05-06 12:36:00,0.000000e+00,206.865234,34.691408,35.452499,40.986353,34.284571,28.856995,0.129883,0.351562,0.141602,0.435547,28.191909,51.299965

In [20]:
df10 = df10
df10.set_index([
	'Tiempo',
], inplace=True)
attrs = {
	'var': 'df10',
	'type': type(df10).__name__,
}
[attrs]
df10

[{'var': 'df10', 'type': 'DataFrame'}]

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
Tiempo,,,,,,,,,,,,,
2017-07-01 08:00:00,6.633393e+01,352.291016,39.330568,36.067589,55.485401,33.841759,34.713011,7.509375,10.081446,6.396680,14.159180,40.533623,28.600006
2017-07-01 08:12:00,5.873533e+01,371.410156,40.237015,36.454180,55.306391,35.115929,34.984612,6.826367,8.688281,6.017188,12.778320,40.410822,28.500004
2017-07-01 08:24:00,7.330124e+01,306.683594,42.924143,39.803396,57.962978,38.862738,36.497345,7.344141,9.495117,6.327344,13.664258,40.086174,28.500004
2017-07-01 08:36:00,7.359566e+01,263.185547,44.400021,41.389423,59.253897,40.636448,37.869467,7.599805,9.619336,7.019141,13.967968,41.802011,28.500004
2017-07-01 08:48:00,7.216714e+01,300.306641,43.409241,40.016947,57.869795,37.751429,38.141232,7.640820,9.582422,6.680078,13.574414,41.188478,28.500004
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-05-06 11:48:00,3.816504e-28,191.533203,40.859182,39.509026,53.035002,38.809961,33.665823,0.247559,0.545898,0.271484,0.688477,12.427644,51.299965
2019-05-06 12:00:00,0.000000e+00,187.421875,37.240042,38.162100,45.844812,34.772854,32.221487,0.134766,0.362793,0.154785,0.394531,3.659730,51.299965
2019-05-06 12:12:00,0.000000e+00,203.500977,35.421877,36.641315,43.335768,33.321487,30.623049,0.122070,0.319824,0.126465,0.371094,11.449250,51.299965
2019-05-06 12:24:00,0.000000e+00,214.321289,34.453516,35.566711,41.824305,32.437502,29.482814,0.099609,0.308594,0.122559,0.379883,27.432148,51.299965
2019-05-06 12:36:00,0.000000e+00,206.865234,34.691408,35.452499,40.986353,34.284571,28.856995,0.129883,0.351562,0.141602,0.435547,28.191909,51.299965

In [21]:
col_start = df9['Inicio']
col_end = df9['Fin']
idx = pd.IntervalIndex.from_arrays(col_start, col_end, closed='left')
df9_interval = df9.set_index(idx)
df9_interval = df9_interval.drop(columns=[
	'Inicio',
	'Fin'
], axis='columns')
df_labels14 = pd.DataFrame(index=df10.index)
df_labels14['Estado de salud'] = 'operativo'
for i, r in df9_interval.iterrows():
	mask = (df_labels14.index >= i.left) & (df_labels14.index < i.right)
	df_labels14.loc[mask, 'Estado de salud'] = r['Tipo de Detención']
attrs = {
	'var': 'df_labels14',
	'type': type(df_labels14).__name__,
}
[attrs]
df_labels14

[{'var': 'df_labels14', 'type': 'DataFrame'}]

                    Estado de salud
Tiempo
2017-07-01 08:00:00       operativo
2017-07-01 08:12:00       operativo
2017-07-01 08:24:00       operativo
2017-07-01 08:36:00       operativo
2017-07-01 08:48:00       operativo
...                             ...
2019-05-06 11:48:00       operativo
2019-05-06 12:00:00       operativo
2019-05-06 12:12:00       operativo
2019-05-06 12:24:00       operativo
2019-05-06 12:36:00       operativo

[80904 rows x 1 columns]

In [22]:
df17 = pd.concat([
	df10,
	df_labels14,
], axis='columns', join='outer')

attrs = {
	'var': 'df17',
	'type': type(df17).__name__,
}
[attrs]
df17

[{'var': 'df17', 'type': 'DataFrame'}]

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting,Estado de salud
Tiempo,,,,,,,,,,,,,,
2017-07-01 08:00:00,6.633393e+01,352.291016,39.330568,36.067589,55.485401,33.841759,34.713011,7.509375,10.081446,6.396680,14.159180,40.533623,28.600006,operativo
2017-07-01 08:12:00,5.873533e+01,371.410156,40.237015,36.454180,55.306391,35.115929,34.984612,6.826367,8.688281,6.017188,12.778320,40.410822,28.500004,operativo
2017-07-01 08:24:00,7.330124e+01,306.683594,42.924143,39.803396,57.962978,38.862738,36.497345,7.344141,9.495117,6.327344,13.664258,40.086174,28.500004,operativo
2017-07-01 08:36:00,7.359566e+01,263.185547,44.400021,41.389423,59.253897,40.636448,37.869467,7.599805,9.619336,7.019141,13.967968,41.802011,28.500004,operativo
2017-07-01 08:48:00,7.216714e+01,300.306641,43.409241,40.016947,57.869795,37.751429,38.141232,7.640820,9.582422,6.680078,13.574414,41.188478,28.500004,operativo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-05-06 11:48:00,3.816504e-28,191.533203,40.859182,39.509026,53.035002,38.809961,33.665823,0.247559,0.545898,0.271484,0.688477,12.427644,51.299965,operativo
2019-05-06 12:00:00,0.000000e+00,187.421875,37.240042,38.162100,45.844812,34.772854,32.221487,0.134766,0.362793,0.154785,0.394531,3.659730,51.299965,operativo
2019-05-06 12:12:00,0.000000e+00,203.500977,35.421877,36.641315,43.335768,33.321487,30.623049,0.122070,0.319824,0.126465,0.371094,11.449250,51.299965,operativo
2019-05-06 12:24:00,0.000000e+00,214.321289,34.453516,35.566711,41.824305,32.437502,29.482814,0.099609,0.308594,0.122559,0.379883,27.432148,51.299965,operativo
2019-05-06 12:36:00,0.000000e+00,206.865234,34.691408,35.452499,40.986353,34.284571,28.856995,0.129883,0.351562,0.141602,0.435547,28.191909,51.299965,operativo

In [23]:
cond = ((df17['Estado de salud'].ne('Pausa')))
df17 = df17[cond]
attrs = {
	'var': 'df17',
	'type': type(df17).__name__,
}
[attrs]
df17

[{'var': 'df17', 'type': 'DataFrame'}]

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting,Estado de salud
Tiempo,,,,,,,,,,,,,,
2017-07-01 08:00:00,6.633393e+01,352.291016,39.330568,36.067589,55.485401,33.841759,34.713011,7.509375,10.081446,6.396680,14.159180,40.533623,28.600006,operativo
2017-07-01 08:12:00,5.873533e+01,371.410156,40.237015,36.454180,55.306391,35.115929,34.984612,6.826367,8.688281,6.017188,12.778320,40.410822,28.500004,operativo
2017-07-01 08:24:00,7.330124e+01,306.683594,42.924143,39.803396,57.962978,38.862738,36.497345,7.344141,9.495117,6.327344,13.664258,40.086174,28.500004,operativo
2017-07-01 08:36:00,7.359566e+01,263.185547,44.400021,41.389423,59.253897,40.636448,37.869467,7.599805,9.619336,7.019141,13.967968,41.802011,28.500004,operativo
2017-07-01 08:48:00,7.216714e+01,300.306641,43.409241,40.016947,57.869795,37.751429,38.141232,7.640820,9.582422,6.680078,13.574414,41.188478,28.500004,operativo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-05-06 11:48:00,3.816504e-28,191.533203,40.859182,39.509026,53.035002,38.809961,33.665823,0.247559,0.545898,0.271484,0.688477,12.427644,51.299965,operativo
2019-05-06 12:00:00,0.000000e+00,187.421875,37.240042,38.162100,45.844812,34.772854,32.221487,0.134766,0.362793,0.154785,0.394531,3.659730,51.299965,operativo
2019-05-06 12:12:00,0.000000e+00,203.500977,35.421877,36.641315,43.335768,33.321487,30.623049,0.122070,0.319824,0.126465,0.371094,11.449250,51.299965,operativo
2019-05-06 12:24:00,0.000000e+00,214.321289,34.453516,35.566711,41.824305,32.437502,29.482814,0.099609,0.308594,0.122559,0.379883,27.432148,51.299965,operativo
2019-05-06 12:36:00,0.000000e+00,206.865234,34.691408,35.452499,40.986353,34.284571,28.856995,0.129883,0.351562,0.141602,0.435547,28.191909,51.299965,operativo

In [24]:
df17 = df17
cond = ((df17['Estado de salud'].eq('operativo')))
df17['Estado de salud'].mask(cond, other=0, inplace=True)

cond = ((df17['Estado de salud'].eq('Falla')))
df17['Estado de salud'].mask(cond, other=1, inplace=True)

attrs = {
	'var': 'df17',
	'type': type(df17).__name__,
}
[attrs]
df17

C:\Users\victo\AppData\Local\Temp\ipykernel_11100\49696495.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df17['Estado de salud'].mask(cond, other=0, inplace=True)
C:\Users\victo\AppData\Local\Temp\ipykernel_11100\49696495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df17['Estado de salud'].mask(cond, other=0, inplace=True)
C:\Users\victo\AppData\Local\Temp\ipykernel_11100\49696495.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df17['Estado de salud'].mask(cond, other=1, inplace=True)
C:\Users\victo\AppData\Local\Temp\ipykernel_11100\49696495.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df17['Estado de salud'].mask(cond, other=1, inplace=True)

[{'var': 'df17', 'type': 'DataFrame'}]

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting,Estado de salud
Tiempo,,,,,,,,,,,,,,
2017-07-01 08:00:00,6.633393e+01,352.291016,39.330568,36.067589,55.485401,33.841759,34.713011,7.509375,10.081446,6.396680,14.159180,40.533623,28.600006,0
2017-07-01 08:12:00,5.873533e+01,371.410156,40.237015,36.454180,55.306391,35.115929,34.984612,6.826367,8.688281,6.017188,12.778320,40.410822,28.500004,0
2017-07-01 08:24:00,7.330124e+01,306.683594,42.924143,39.803396,57.962978,38.862738,36.497345,7.344141,9.495117,6.327344,13.664258,40.086174,28.500004,0
2017-07-01 08:36:00,7.359566e+01,263.185547,44.400021,41.389423,59.253897,40.636448,37.869467,7.599805,9.619336,7.019141,13.967968,41.802011,28.500004,0
2017-07-01 08:48:00,7.216714e+01,300.306641,43.409241,40.016947,57.869795,37.751429,38.141232,7.640820,9.582422,6.680078,13.574414,41.188478,28.500004,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-05-06 11:48:00,3.816504e-28,191.533203,40.859182,39.509026,53.035002,38.809961,33.665823,0.247559,0.545898,0.271484,0.688477,12.427644,51.299965,0
2019-05-06 12:00:00,0.000000e+00,187.421875,37.240042,38.162100,45.844812,34.772854,32.221487,0.134766,0.362793,0.154785,0.394531,3.659730,51.299965,0
2019-05-06 12:12:00,0.000000e+00,203.500977,35.421877,36.641315,43.335768,33.321487,30.623049,0.122070,0.319824,0.126465,0.371094,11.449250,51.299965,0
2019-05-06 12:24:00,0.000000e+00,214.321289,34.453516,35.566711,41.824305,32.437502,29.482814,0.099609,0.308594,0.122559,0.379883,27.432148,51.299965,0
2019-05-06 12:36:00,0.000000e+00,206.865234,34.691408,35.452499,40.986353,34.284571,28.856995,0.129883,0.351562,0.141602,0.435547,28.191909,51.299965,0

In [25]:
df49 = df17.drop([
	'Estado de salud',
], axis='columns')
attrs = {
	'var': 'df49',
	'type': type(df49).__name__,
}
[attrs]
df49

[{'var': 'df49', 'type': 'DataFrame'}]

,Corriente,Presión C. Eje,T° Retorno,T° socket Linner,T° Excéntrica,T° Alimentación,T° Desc. C. Eje,Salto anillo A,Salto anillo B,Salto anillo C,Salto anillo D,Nivel Taza,Setting
Tiempo,,,,,,,,,,,,,
2017-07-01 08:00:00,6.633393e+01,352.291016,39.330568,36.067589,55.485401,33.841759,34.713011,7.509375,10.081446,6.396680,14.159180,40.533623,28.600006
2017-07-01 08:12:00,5.873533e+01,371.410156,40.237015,36.454180,55.306391,35.115929,34.984612,6.826367,8.688281,6.017188,12.778320,40.410822,28.500004
2017-07-01 08:24:00,7.330124e+01,306.683594,42.924143,39.803396,57.962978,38.862738,36.497345,7.344141,9.495117,6.327344,13.664258,40.086174,28.500004
2017-07-01 08:36:00,7.359566e+01,263.185547,44.400021,41.389423,59.253897,40.636448,37.869467,7.599805,9.619336,7.019141,13.967968,41.802011,28.500004
2017-07-01 08:48:00,7.216714e+01,300.306641,43.409241,40.016947,57.869795,37.751429,38.141232,7.640820,9.582422,6.680078,13.574414,41.188478,28.500004
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-05-06 11:48:00,3.816504e-28,191.533203,40.859182,39.509026,53.035002,38.809961,33.665823,0.247559,0.545898,0.271484,0.688477,12.427644,51.299965
2019-05-06 12:00:00,0.000000e+00,187.421875,37.240042,38.162100,45.844812,34.772854,32.221487,0.134766,0.362793,0.154785,0.394531,3.659730,51.299965
2019-05-06 12:12:00,0.000000e+00,203.500977,35.421877,36.641315,43.335768,33.321487,30.623049,0.122070,0.319824,0.126465,0.371094,11.449250,51.299965
2019-05-06 12:24:00,0.000000e+00,214.321289,34.453516,35.566711,41.824305,32.437502,29.482814,0.099609,0.308594,0.122559,0.379883,27.432148,51.299965
2019-05-06 12:36:00,0.000000e+00,206.865234,34.691408,35.452499,40.986353,34.284571,28.856995,0.129883,0.351562,0.141602,0.435547,28.191909,51.299965

In [26]:
df50 = df17[[
	'Estado de salud',
]]
attrs = {
	'var': 'df50',
	'type': type(df50).__name__,
}
[attrs]
df50

[{'var': 'df50', 'type': 'DataFrame'}]

                    Estado de salud
Tiempo
2017-07-01 08:00:00               0
2017-07-01 08:12:00               0
2017-07-01 08:24:00               0
2017-07-01 08:36:00               0
2017-07-01 08:48:00               0
...                             ...
2019-05-06 11:48:00               0
2019-05-06 12:00:00               0
2019-05-06 12:12:00               0
2019-05-06 12:24:00               0
2019-05-06 12:36:00               0

[80889 rows x 1 columns]

In [27]:
def datetime_window(dfx, dfy, dfy_total, scaler, size, periods, y_choose='last', ahead=''):
    catcolsx = dfx.select_dtypes(['category']).columns
    dfx[catcolsx] = dfx[catcolsx].apply(lambda x: x.cat.codes)

    catcolsy = dfy.select_dtypes(['category']).columns
    dfy[catcolsy] = dfy[catcolsy].apply(lambda x: x.cat.codes)

    catcolsy_total = dfy_total.select_dtypes(['category']).columns
    dfy_total[catcolsy_total] = dfy_total[catcolsy_total].apply(lambda x: x.cat.codes)

    ind = []
    x = []
    y = []

    def get_windows(win):
        if (win.shape[0] != periods):
            return np.nan
        
        if (y_choose == 'ahead'):
            wy = dfy.loc[win.index, :]
            try:
                wy = dfy_total.loc[wy.index[-1] + pd.Timedelta(ahead)]
                y.append(wy)

                wx = dfx.loc[win.index, :]
                x.append(wx)

                ind.append(win.index[0])
            except:
                pass
        else:
            wx = dfx.loc[win.index, :]
            x.append(wx)

            wy = dfy.loc[win.index, :]
            if (y_choose == 'last'):
                wy = wy.iloc[-1]
            elif (y_choose == 'first'):
                wy = wy.iloc[0]
            y.append(wy)

            ind.append(win.index[0])
        
        return np.nan

    dfx.iloc[:, 0].rolling(size).apply(get_windows)
    
    return x, y, ind

# --------------------------------------------------------------------------------------
def print_list_shape(lst):
    s = ''
    if (len(lst) > 0):
        s += str(len(lst))
        s += ' x ' + str(np.array(lst[0]).shape)
    else:
        s += 'empty'
        
    return s

# --------------------------------------------------------------------------------------
def normal_anomal_split(dfx, dfy, size, periods, y_choose='last', ahead='', custom_normal_split=False, normal_test_ratio=0.1, scaler='MinMaxScaler'):
    
    if (scaler == 'MinMaxScaler'):
        myscaler = MinMaxScaler(feature_range=(0, 1))
    elif (scaler == 'StandardScaler'):
        myscaler = StandardScaler()
    elif(scaler == 'RobustScaler'):
        myscaler = RobustScaler(with_centering=True, with_scaling=True, quantile_range=(25, 75))
    
    x_windowed, y_windowed, windows_ind = datetime_window(dfx=dfx, dfy=dfy, dfy_total=dfy, scaler=myscaler, size=size, periods=periods, y_choose=y_choose, ahead=ahead)
    
    
    x_normal = []
    y_normal = []
    x_anomal = []
    y_anomal = []
    for (i, wy) in enumerate(y_windowed):
        if wy.iloc[0] == 0:
            x_normal.append(x_windowed[i])
            y_normal.append(y_windowed[i])
        else:
            x_anomal.append(x_windowed[i])
            y_anomal.append(y_windowed[i])
    
    
    normal_indices = [i for i in range(len(x_normal))]
    normal_indices_permuted = np.random.permutation(normal_indices)
    
    length = len(x_normal)
    length_test = round(length * normal_test_ratio)
    
    if custom_normal_split:
        normal_test_indices = normal_indices_permuted[:length_test]
        normal_train_indices = normal_indices_permuted[length_test:]
    else:
        normal_test_indices = normal_indices_permuted[:len(y_anomal)]
        normal_train_indices = normal_indices_permuted[len(y_anomal):]
    
    
    x_normal_train = [x_normal[i] for i in normal_train_indices]
    x_normal_test = [x_normal[i] for i in normal_test_indices]
    
    
    x_normal_train_total = pd.concat(x_normal_train)
    x_normal_train_total = x_normal_train_total[~x_normal_train_total.index.duplicated(keep='first')]
    x_normal_train_total.sort_index(inplace=True)
    
    myscaler.fit(x_normal_train_total.to_numpy())
    
    x_train = []
    for wx in x_normal_train:
        wx = wx.to_numpy()
        wx = np.squeeze(myscaler.transform(wx))
        x_train.append(wx)
    
    
    x_test = []
    y_test = []
    for wx in x_normal_test:
        wx = wx.to_numpy()
        wx = np.squeeze(myscaler.transform(wx))
        x_test.append(wx)
        y_test.append(0)
        
    for wx in x_anomal:
        wx = wx.to_numpy()
        wx = np.squeeze(myscaler.transform(wx))
        x_test.append(wx)
        y_test.append(1)
    
    x_mix = []
    for wx in x_windowed:
        wx = wx.to_numpy()
        wx = np.squeeze(myscaler.transform(wx))
        x_mix.append(wx)
    
    y_mix = []
    for wy in y_windowed:
        wy = wy.to_numpy()
        wy = wy[0]
        y_mix.append(wy)
        
    i_mix = windows_ind

    
    return x_train, x_test, y_test, x_mix, y_mix, i_mix, myscaler
x_train, x_test, y_test, x_mix, y_mix, i_mix, myscaler = normal_anomal_split(
	dfx=df49, dfy=df50
	, size='120T', periods=5, y_choose='last', ahead=''
	, custom_normal_split=True, normal_test_ratio=0.2, scaler='MinMaxScaler')

df49 = {
	'x_train': np.array(x_train),
	'x_test': np.array(x_test),
	'y_test': np.array(y_test),
	'x_mix': np.array(x_mix),
	'y_mix': np.array(y_mix),
	'i_mix': i_mix,
	'myscaler': myscaler,
}

attrs = {
	'var': 'df49',
	'type': type(df49).__name__,
}
[attrs]

{
	'x_train': print_list_shape(x_train),
	'x_test': print_list_shape(x_test),
	'y_test': print_list_shape(y_test),
}

np.squeeze(df49['x_train'])
np.squeeze(df49['x_test'])
np.squeeze(df49['y_test'])

C:\Users\victo\AppData\Local\Temp\ipykernel_11100\1918727449.py:46: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  dfx.iloc[:, 0].rolling(size).apply(get_windows)

[{'var': 'df49', 'type': 'dict'}]

{'x_train': '1 x (5, 13)', 'x_test': 'empty', 'y_test': 'empty'}

array([[0.51133455, 0.82333833, 0.        , 0.        , 0.04534772,
        0.        , 0.        , 0.838609  , 1.        , 0.37875253,
        1.        , 0.26077571, 1.        ],
       [0.        , 1.        , 0.1788056 , 0.07264242, 0.        ,
        0.18752439, 0.07922498, 0.        , 0.        , 0.        ,
        0.        , 0.18920667, 0.        ],
       [0.98018763, 0.40192381, 0.7088684 , 0.70197737, 0.67297874,
        0.73895638, 0.52048404, 0.63573136, 0.57913911, 0.30955175,
        0.64158395, 0.        , 0.        ],
       [1.        , 0.        , 1.        , 1.        , 1.        ,
        1.        , 0.92072717, 0.94964029, 0.66830191, 1.        ,
        0.86152737, 1.        , 0.        ],
       [0.90387048, 0.34300049, 0.80455879, 0.74210461, 0.64937308,
        0.57540084, 1.        , 1.        , 0.64180584, 0.66159849,
        0.57652065, 0.64242941, 0.        ]])

array([], dtype=float64)

array([], dtype=float64)

In [28]:
file = os.path.join('C:/Users/victo/OneDrive/Escritorio/Estudios USM/Ingenieria/Computacion aplicada/', 'Chancador trabajo computacion 12M')
np.savez(file, x_train=df49['x_train'], x_test=df49['x_test'], y_test=df49['y_test'], x_mix=df49['x_mix'], y_mix=df49['y_mix'], i_mix=df49['i_mix'])
scaler_file = os.path.join('C:/Users/victo/OneDrive/Escritorio/Estudios USM/Ingenieria/Computacion aplicada/', 'scaler.joblib')
joblib.dump(df49['myscaler'], scaler_file)
attrs = {
	'var': 'empty',
	'type': 'empty',
}
[attrs]
'npz file saved'

['C:/Users/victo/OneDrive/Escritorio/Estudios USM/Ingenieria/Computacion aplicada/scaler.joblib']

[{'var': 'empty', 'type': 'empty'}]

'npz file saved'